### ISSUE TITLE
Data not displayed from kibana

### ISSUE THREAD

**Issue by mareban** [usiusi360/vuls-log-converter#3]
Hello,

Great work !

We've some problems : 

- to use vuls-log-convert, we have to scan with vuls, but if we do not go through the UI (vuls tui) before convert, nothing is sent to ES !! Is it normal ?
- the script doesn't create the index in ES, we have to create the index manually, the firts bulk insert is OK, but the next are stored in ES but not displayed in Kibana !! Can you provide an index template please ?

Thanks for your help.

**Comment by mareban** [comment]
Yes, we have to run a report first : vuls report -format-json
To index all scans in ES 2.1.4, we've changed all ScannedAt with Date.now() !

Thx

**Comment by usiusi360** [comment]
:ok_hand:
